# Site settings
title:          Thoughts
description:    "Blog | Abhishek Balam"
baseurl:        ""
url:            ""

# Author
author:
  name:         Abhishek Balam
  url:          https://abhishekbalam.xyz
  email:        abhishekbalam@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:title
paginate:       5
