# Site settings
title:          Blog
description:    "Personal Blog | Abhishek Balam"
baseurl:        "/nZ2302"
url:            "http://personal.abhishekbalam.xyz"

# Author
author:
  name:         Abhishek Balam
  url:          https://abhishekbalam.xyz
  email:        abhishekbalam@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
